server:
  port: 8080

# 引入依赖spring-boot-starter-actuator，并将gateway端点暴露
# http://localhost:8080/actuator/gateway/routes
management:
  endpoints:
    web:
      exposure:
        include: gateway

spring:
  profiles:
    active: add_request_header_route
    # active: rewritepath_route
    # active: elapse_route

---
# 添加header X-Request-Foo, Bar
# curl localhost:8080
spring:
  cloud:
    gateway:
      routes:
      - id: add_request_header_route
        uri: http://httpbin.org:80/get
        filters:
        - AddRequestHeader=X-Request-Foo, Bar
        predicates:
        - After=2021-08-09T18:00:00.000+08:00[Asia/Shanghai]
  profiles: add_request_header_route

---
# 将/foo/(?.*)重写为{segment}，然后转发到https://blog.csdn.net
# 访问localhost:8080/foo/lzmzzw
spring:
  cloud:
    gateway:
      routes:
      - id: rewritepath_route
        uri: https://blog.csdn.net
        predicates:
        - Path=/foo/**
        filters:
        - RewritePath=/foo/(?<segment>.*), /$\{segment}
  profiles: rewritepath_route

---
# 工厂模式，使用RequestTimeGatewayFilterFactory构建filter
spring:
  cloud:
    gateway:
      routes:
      - id: elapse_route
        uri: http://httpbin.org:80/get
        filters:
        - RequestTime=true
        predicates:
        - Path=/foo/**
  profiles: elapse_route