server:
  port: 8765

spring:
  application:
    name: service-feign-hystrix

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# Feign是自带断路器，在D版本的Spring Cloud之后，默认关闭，需要在配置文件中配置打开
feign:
  hystrix:
    enabled: true

