spring:
  application:
    name: service-zipkin-1
  zipkin:
    base-url: http://localhost:9411
    # 关闭服务发现，否则Spring Cloud会把zipkin的url当做服务名称
    discoveryClientEnabled: false
    sender:
      # 设置使用http的方式传输数据
      type: web
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      # zipkin默认是10%的抽样，所以要配置1.0
      probability: 1.0

server:
  port: 8988
